[settings]
timeout = 1000

[relaychain]
default_command = "./bin/polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  ws_port = 9944
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  ws_port = 9945
  validator = true

[[parachains]]
id = 1000
add_to_genesis = true
cumulus_based = true
chain = "asset-hub-westend-local"

  [[parachains.collators]]
  name = "asset-hub-collator-1"
  command = "./bin/asset-hub"
  ws_port = 9946

  [[parachains.collators]]
  name = "asset-hub-collator-2"
  command = "./bin/asset-hub"
  ws_port = 9947

[types.Header]
number = "u64"
weight = "u64"
parent_hash = "Hash"
post_state = "Hash"


